name: proximity_commercant
description: Proximity Commercant mobile app for sellers.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  proximity:
    path: ../
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.3
  url_launcher: ^6.1.4
  http: ^0.13.4
  dio: ^4.0.6
  google_maps_flutter: ^2.1.8
  location: ^4.2.0
  geocoding: ^2.0.4
  image_picker: ^0.8.5+3
  shimmer: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  showcaseview: 2.0.0+1
  restart_app: ^1.1.2
  flutter_phoenix: ^1.1.0
  onesignal_flutter: ^3.5.0
  pay: ^1.0.10
  fl_chart: ^0.62.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.3

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  image: assets/proximity-logo-light.png
  image_dark: assets/proximity-logo-dark.png
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/proximity-logo-light.png
    - assets/orders.png
    - assets/store_creation.png 
    - assets/policy.png
    - assets/promote.png
    - assets/proximity-logo-dark.png
    - assets/img/profile-pic.png
    - assets/img/ar.png
    - assets/img/fr.png
    - assets/img/en.png
    - assets/img/map-pin.png
    - assets/img/illustration-1.png
    - assets/img/illustration-2.png
    - assets/img/illustration-3.png
    - assets/img/facebook.png
    - assets/img/google.png
    - assets/img/twitter.png
    - assets/img/products/product-0-0.png
    - assets/img/products/product-0-1.png
    - assets/img/products/product-0-variant-0.png
    - assets/img/products/product-0-variant-1.png
    - assets/img/products/product-0-variant-2.png
    - assets/img/products/product-0-variant-3.png
    - assets/img/products/product-0-variant-4.png
    - assets/img/products/product-0-variant-5.png
    - assets/img/products/product-0-variant-6.png
    - assets/img/products/product-0-variant-7.png
    - assets/img/products/product-1.png
    - assets/img/products/product-2.png
    - assets/img/products/product-3.png
    - assets/img/products/product-4.png
    - assets/img/products/product-5.png
    - assets/img/products/product-6.png
    - assets/img/products/product-7.png
    - assets/img/products/product-8.png
    - assets/img/products/product-9.png
    - assets/img/products/product-10.png
    - assets/img/products/product-11.png
    - assets/img/stores/store-map.png
    - assets/img/ads/ad_1.png
    - assets/img/ads/ad_2.png
    - assets/img/ads/ad_3.png
    - assets/img/ads/ad_4.png
    - assets/img/ads/ad_5.png
    - assets/img/welcome.png
    - assets/img/return_icon.png
    - assets/img/return_icon2.png
    - assets/img/refund_icon.png
    - assets/img/refund_icon2.png
