name: proximity
description: Proximity Design System.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  google_maps_flutter: ^2.1.8
  location: ^4.2.0
  geocoding: ^2.0.4
  image_picker: ^0.8.5+3
  shimmer: ^2.0.0
  intl_phone_field: ^3.1.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: Nunito
      fonts:
        - asset: lib/fonts/Nunito-Regular.ttf
        - asset: lib/fonts/Nunito-Light.ttf
          weight: 300
        - asset: lib/fonts/Nunito-SemiBold.ttf
          weight: 600
    - family: Proximity
      fonts:
        - asset: lib/icons/proximity_icons.ttf