import 'package:flutter/material.dart';
import 'package:proximity/config/colors.dart';

const _fontFamily = 'Nunito';
const _packageName = 'proximity';

/// Light TextTheme
const TextTheme lightTextTheme = TextTheme(
    headline1: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextLightColor,
        fontSize: 48,
        fontWeight: FontWeight.w300),
    headline2: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextLightColor,
        fontSize: 34,
        fontWeight: FontWeight.w600),
    headline3: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextLightColor,
        fontSize: 24,
        fontWeight: FontWeight.w600),
    headline4: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextLightColor,
        fontSize: 20,
        fontWeight: FontWeight.w600),
    headline5: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextLightColor,
        fontSize: 14,
        fontWeight: FontWeight.w600),
    headline6: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: secondaryTextLightColor,
        fontSize: 14,
        fontWeight: FontWeight.w600),
    subtitle1: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextLightColor,
        fontSize: 26,
        fontWeight: FontWeight.w300),
    subtitle2: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextLightColor,
        fontSize: 14,
        fontWeight: FontWeight.w400),
    bodyText1: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextLightColor,
        fontSize: 10,
        fontWeight: FontWeight.w600),
    bodyText2: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: secondaryTextLightColor,
        fontSize: 10,
        fontWeight: FontWeight.w600),
    button: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextLightColor,
        fontSize: 20,
        fontWeight: FontWeight.w600),
    caption: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: secondaryTextLightColor,
        fontSize: 8,
        fontWeight: FontWeight.w600));

/// Dark TextTheme
const TextTheme darkTextTheme = TextTheme(
    headline1: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextDarkColor,
        fontSize: 48,
        fontWeight: FontWeight.w300),
    headline2: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextDarkColor,
        fontSize: 34,
        fontWeight: FontWeight.w600),
    headline3: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextDarkColor,
        fontSize: 24,
        fontWeight: FontWeight.w600),
    headline4: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextDarkColor,
        fontSize: 20,
        fontWeight: FontWeight.w600),
    headline5: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextDarkColor,
        fontSize: 14,
        fontWeight: FontWeight.w600),
    headline6: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: secondaryTextDarkColor,
        fontSize: 14,
        fontWeight: FontWeight.w600),
    subtitle1: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextDarkColor,
        fontSize: 26,
        fontWeight: FontWeight.w300),
    subtitle2: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextDarkColor,
        fontSize: 14,
        fontWeight: FontWeight.w400),
    bodyText1: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextDarkColor,
        fontSize: 12,
        fontWeight: FontWeight.w600),
    bodyText2: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: secondaryTextDarkColor,
        fontSize: 12,
        fontWeight: FontWeight.w600),
    button: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: primaryTextDarkColor,
        fontSize: 20,
        fontWeight: FontWeight.w600),
    caption: TextStyle(
        fontFamily: _fontFamily,
        package: _packageName,
        color: secondaryTextDarkColor,
        fontSize: 10,
        fontWeight: FontWeight.w600));